### ISSUE TITLE
Can't convert sample MMAX2 out of the box

### ISSUE THREAD

**Issue by thomaskrause** [korpling/pepperModules-MMAX2Modules#3]
The example MMAX file from their software release do not work because there are "\" in the common_paths.xml

**Comment by thomaskrause** [comment]
This seems to be a problem in mmax2 wrapper:

https://bitbucket.org/commul/mmax2_java_wrapper/src/1cc96671c421a712afc47f7ffbf40ded358d446b/src/main/java/edu/eurac/commul/annotations/mmax2/mmax2wrapper/CorpusFactory.java?at=master&fileviewer=file-view-default#CorpusFactory.java-65

**Comment by lnicolas** [comment]
I'll look into it as soon as I can

**Comment by lnicolas** [comment]
I made the fixes and committed/pushed to the master branches. 
Is it fixed on your side too ?

**Comment by thomaskrause** [comment]
Yes, it seem to be fixed in the master branch. Our Jenkins build-bot seems to be confused by the direct commits to the master branch and did not perform a proper release. I try to fix these issues (but this will increase the version number to 1.0.4 and add some commits).

**Comment by lnicolas** [comment]
Sorry, I had forgotten that committing on the master branch was triggering releases. 
Could you tell me a bit more about that so that I follow the official/officious workflow next time ?

**Comment by thomaskrause** [comment]
The expectation of the build bot is that development is done on a "develop" branch with SNAPSHOT versions. Each commit/push to the develop branch will trigger a snapshot build which is also deployed to a Maven snapshot repository.

To make a release the current version of develop is merged into master. The version must still be "X.X.X-SNAPSHOT": the build bot will add some commits to change the version number to a stable version and deploy the releases to Maven Central. I have to manually confirm the release on the https://oss.sonatype.org/ interface, so that no accidental release can happen (thus I need to know when something should be released). 

The build-bot also will merge all changes back from master to develop. Thus whenever there is a deviation from the "normal" release process I also have to merge the current master branch manually into develop before pushing something to "master" to avoid any conflicts when the build bot merges master back (it can't resolve such conflicts on it's own and will fail).

I'm currently preparing the release and doing the conflict solving for the merge from master to develop: I've choosen to use develop whenever possible but you might want to check the result afterwards.

**Comment by thomaskrause** [comment]
Ok, I managed to make a new release (it's 1.0.6) and this is also merged into the develop branch. Since there have been some conflicts between develop and master branch you might want to have a look at the develop branch if my conflict resolution is ok.
